language: node_js
node_js:
- node
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_04c64bd82511_key -iv $encrypted_04c64bd82511_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host vultr.ralfz.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- yarn
script:
- yarn run build
after_success:
- scp -r dist ralfz@vultr.ralfz.com:/var/www/vdo